apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: is-renovate-bot
spec:
  source:
    git:
      uri: >-
        https://github.com/eclipsesystemsltd/renovate-docker.git
      ref:
      commit: "latest"
    type: Git
  strategy:
    dockerStrategy:
      buildArgs:
      type: Docker
  output:
    to:
      kind: "ImageStreamTag"
      name: "is-renovate-bot:latest"
