apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: is-renovate-bot
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 60
  suspend: true
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "cronjob-is-renovate-bot"
        spec:
          restartPolicy: Never
          containers:
            - image: is-renovate-bot
              name: is-renovate-bot
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/config/config.json
                  subPath: config.json
              env:
                - name: RENOVATE_CONFIG_FILE
                  value: "/etc/config/config.json"
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
