apiVersion: v1
kind: DeploymentConfig
metadata:
  name: is-renovate-bot
spec:
  template:
    metadata:
      labels:
        name: is-renovate-bot
    spec:
      containers:
        - image: is-renovate-bot
          name: is-renovate-bot
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config/config.json
              subPath: config.json
          env:
            - name: RENOVATE_CONFIG_FILE
              value: "/etc/config/config.json"
      volumes:
        - name: config-volume
          configMap:
            name: renovate-config
  replicas: 1
  selector:
    name: is-renovate-bot
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - is-renovate-bot
        from:
          kind: ImageStreamTag
          name: 'is-renovate-bot:latest'
  strategy:
    type: Rolling
