apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: is-renovate-bot
  name: is-renovate-bot
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: is-renovate-bot:latest
      generation: 1
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
status:
  dockerImageRepository: docker-registry.default.svc:5000/is-renovate-bot
